on: push
name: Main
env:
  FIRST_NAME: Test
jobs:
  check_scopes:
    name: check_scopes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install @actions/core
    - run: node ./scripts/set-scopes.js
    - run: echo "::set-env name=FIRST_NAME::lol"
  prepare_js:
    name: prepare_js
    runs-on: ubuntu-latest
    needs: check_scopes
    steps:
      - uses: actions/checkout@master
      - run: echo "Ceci est un test $FIRST_NAME"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
  lint:
    name: lint1
    needs: prepare_js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: Lint
      uses: CultureHQ/actions-yarn@master
      with:
        args: test:u
  lint2:
    name: changed-files
    needs: prepare_js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
    - run: npm run test:file
