on: push
name: Main
jobs:
  prepare_js:
    name: prepare_js
    runs-on: ubuntu-latest
    steps:
      - run: psql -c 'create database oc;' -U postgres
      - uses: actions/checkout@master
      - run: node ./scripts/set-scopes.js
      - name: Cache node modules
        if: env.JS_MODIFIED == 'true'
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        if: env.JS_MODIFIED == 'true'
        run: yarn install
  lint:
    name: lint1
    needs: prepare_js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: node ./scripts/set-scopes.js
      - name: Cache node module
        if: env.JS_MODIFIED == 'true'
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: Lint
        if: env.JS_MODIFIED == 'true'
        run: yarn test:u
  changed_files:
    name: changed-files
    needs: prepare_js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: node ./scripts/set-scopes.js
      - name: Cache node modules
        if: env.JS_MODIFIED == 'true'
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: run test:file
        if: env.JS_MODIFIED == 'true'
        run: npm run test:file
