on: push
name: Main
jobs:
  prepare_js:
    name: prepare_js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: node ./scripts/set-scopes.js
      - run: echo 'Test $JS_MODIFIED'
      - name: Cache node modules
        if: 'a' == 'b'
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        if: 'a' == 'b'
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
  lint:
    name: lint1
    needs: prepare_js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache node module
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: test:u
  lint2:
    name: changed-files
    needs: prepare_js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      - run: npm run test:file
