on: push
name: Main
jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
  lint:
    name: lint1
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: Lint
      uses: CultureHQ/actions-yarn@master
      with:
        args: test:u
  lint2:
    name: changed-files
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: testrun
    - run: chmod 776 ./scripts/changed-files.js
    - run: npm run test:file
